EmployeeManagementSystem/urls.py
from django.contrib import admin
from django.urls import path
from public.views import Index,About,Contact,Services
from Admin.views import (
    Login,
    Logout,
    Signup,
    AdminSignup,
    SendEmailForForgotPassword,
    ForgotPassword,
    ChangePass,
    Addevent,
    Assetmanage,
    Recruitnotice,
    Resultpublish,
    ManageEmployee,
    Attendance1,
    TimeSheet,
    LeaveApplication,

    AssignInterview,
    SearchCandidate,
    AcceptCandidate,
    RejectedCandidate,
    Interviews,
    DeleteInterview,
    AddFeedback,
    AssignWork,
    GivenWork,
    AssignedWork,
    StartWork,
    DeleteWork,
    CompletedWork,
    Profile,
    EditProfile,
    AllUsers,
    AllHr,
    Managers,
    Employees,
    UserDetails,
    DeleteUser,
    EditUser,
    Submitted,
    AddEmployee,
    AttendanceDetails,
    DeleteAttendance,
    EditAttendance,
    TimesheetDetails,
    DeleteTimesheet,
    LaDetails,
    Approve,
    DeleteLa
)

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Index, name='index'),
    path('about/',About),
    path('contact/',Contact),
    path('services/',Services),
    path('login/',Login, name='login'),
   

    path('profile/',Profile, name = 'profile'),
    path('edit-profile/',EditProfile, name = 'edit-profile'),
    path('users/', AllUsers, name='users'),
    path('all-hr/', AllHr, name='all-hr'),
    path('managers/', Managers, name='managers'),
    path('employees/', Employees, name='employees'),
    path("user-details/<int:id>/", UserDetails, name="user-details"),
    path('edit-user/<int:id>/', EditUser, name="edit-user"),
    path('delete-user/<int:id>/', DeleteUser, name='delete-user'),
    path('add-event/',Addevent, name= 'add-event'),
    path('asset-manage/',Assetmanage, name='asset-manage'),
    path('attendance/',Attendance1, name='attendance'),
    path('attendance-details/',AttendanceDetails, name='attendance-details'),
    path('delete-attendance/<int:id>/', DeleteAttendance, name='delete-attendance'),
    path('edit-attendance/<int:id>/', EditAttendance, name="edit-attendance"),
    path('submitted/',Submitted, name='submitted'),
    path('timesheet/',TimeSheet, name='timesheet'),
    path('timesheet-details/',TimesheetDetails, name='timesheet-details'),
    path('delete-timesheet/<int:id>/', DeleteTimesheet, name='delete-timesheet'),
    path('leave-application/',LeaveApplication, name= 'leave-application'),
    path('la-details/',LaDetails, name='la-details'),
    path('delete-la/<int:id>/', DeleteLa, name='delete-la'),
    path("approve/<int:id>/", Approve, name="approve"),

    path('assign-interview/', AssignInterview, name='assign-interview'),
    path('search-candidate/', SearchCandidate, name='search-candidate'),
    path('interviews/',Interviews, name= 'interviews'),
    path('add-feedback/<int:id>/', AddFeedback, name='add-feedback'),
    path('accept-candidate/<int:id>/', AcceptCandidate, name='accept-candidate'),
    path('reject-candidate/<int:id>/', RejectedCandidate, name='reject-candidate'),
    path('delete-interview/<int:id>/', DeleteInterview, name='delete-interview'),

    path('assign-work/',AssignWork, name= 'assign-work'),
    path('assigned-work/', AssignedWork, name='assigned-work'),
    path('given-work/', GivenWork, name='given-work'),
    path('delete-work/<int:id>/', DeleteWork, name='delete-work'),

    path('start-work/<int:id>/', StartWork, name='start-work'),
    path('completed-work/<int:id>/', CompletedWork, name='completed-work'),

    path('manage-employee/',ManageEmployee, name='manage-employee'),
    path('add-employee/',AddEmployee, name='add-employee'),
    path('result-publish/',Resultpublish, name='result-publish'),
    path('recruit-notice/',Recruitnotice, name='recruit-notice'),
    path('changepass/',ChangePass, name ='changepass'),
    path('logout/',Logout),
    path('signup/',Signup),
    path('adminsignup/',AdminSignup, name= 'adminsignup'),
    path('email-forgotpassword/',SendEmailForForgotPassword, name='email-forgotpassword'),
    path('forgot-password/', ForgotPassword, name='forgot-password'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Admin/models.py
from django.db import models
import random
from django.contrib.auth.models import User
# Create your models here.
class UserProfile(models.Model):

    USER_TYPES = [
        ('Manager', 'Manager'),
        ('Admin', 'Admin'),
        ('Employee', 'Employee'),
        ('HR', 'HR')
    ]
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    profilePicture = models.ImageField(blank=True, null=True)
    contact_No = models.IntegerField()
    dob = models.DateField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    userType = models.CharField(max_length=15, choices=USER_TYPES, default='Employee')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.user.username


class OTP(models.Model):
    def Get_OTP():
        return random.randint(100000, 999999)
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    otp = models.IntegerField(default=Get_OTP)
    created_at = models.DateTimeField(auto_now_add=True)


class Attendance(models.Model):

    STATUS = [
        ('Absent', 'Absent'),
        ('Present', 'Present')        
    ]
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    date = models.DateField()
    in_time = models.TimeField()
    out_time = models.TimeField()
    status = models.CharField(max_length=15, choices=STATUS, default='Present')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
      return self.user.userType


class Timesheet(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    name= models.CharField(max_length=30,null=True,blank=True)
    contact_No = models.IntegerField()
    date = models.DateField(null=True,blank=True)
    status = models.CharField(max_length=20,null=True,blank=True)
    task= models.CharField(max_length=50,null=True,blank=True)
    assignby= models.CharField(max_length=30,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
      return self.user.userType

class Leaveapplication(models.Model):
    STATUS = (
        ('Pending','Pending'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected')
    )
    def GenID():
        return random.randint(10000000000, 99999999999)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    from_date = models.DateField(null=True,blank=True)
    to_date = models.DateField(null=True,blank=True)
    leaveType = models.CharField(max_length=30)
    reasons= models.CharField(max_length=300,null=True,blank=True)
    leave_id = models.CharField(max_length=30, default=f'LA{GenID()}')
    status = models.CharField(max_length=20, choices=STATUS, default="Pending")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
      return "User " +self.user.user.username + "has applied leave application from " + str(self.from_date) + " to " + str(self.to_date) 


class AddEvent(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    date = models.DateField(null=True,blank=True)
    ename = models.CharField(max_length=30,null=True,blank=True)
    venue= models.CharField(max_length=100,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
      return self.user.userType

class RecruitNotice(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    title = models.CharField(max_length=30,null=True,blank=True)
    description= models.CharField(max_length=200,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
      return self.user.userType


class ResultPublish(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    date = models.DateField(null=True,blank=True)
    ename = models.CharField(max_length=30,null=True,blank=True)
    description= models.CharField(max_length=100,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
      return self.user.userType

class Interview(models.Model):
    STATUS = (
        ('Pending','Pending'),
        ('Selected', 'Selected'),
        ('Rejected', 'Rejected')
    )
    def GenID():
        return random.randint(10000000000, 99999999999)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    candidate_name = models.CharField(max_length=255,null=True,blank=True)
    candidate_email = models.CharField(max_length=100)
    candidate_description = models.TextField()  
    feedback= models.CharField(max_length=255,null=True,blank=True)
    interview_id = models.CharField(max_length=30, default=f'IN{GenID()}')
    status = models.CharField(max_length=20, choices=STATUS, default="Pending")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
      return self.user.userType



class Assignprojects(models.Model):
    STATUS = (
        ('Pending','Pending'),
        ('Completed', 'Completed'),
        ('In Progress', 'In Progress')
    )
    manager = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='manager')
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    pname = models.CharField(max_length=255)
    description = models.TextField()
    date = models.DateField(null=True,blank=True)
    deadline = models.DateField(null=True,blank=True)
    status = models.CharField(max_length=20, choices=STATUS, default="Pending")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
      return "Manager "+ self.manager.user.first_name + self.manager.user.last_name + " Assigned a Work to " + self.user.user.first_name + self.user.user.last_name

Admin/templates/ForgotPassEmail.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <!-- Basic Page Info -->
    <meta charset="utf-8">
    <title>DeskApp - Bootstrap Admin Dashboard HTML Template</title>

    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'vendors/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'vendors/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'vendors/images/favicon-16x16.png' %}">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/core.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/icon-font.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/style.css' %}">


    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119386393-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-119386393-1');
    </script>
</head>

<body>
    <div class="login-header box-shadow">
        <div class="container-fluid d-flex justify-content-between align-items-center">
            <div class="brand-logo">
                <a href="login.html">
                    <img src="{% static 'vendors/images/logo-icon.png' %}" alt="">
                </a>
            </div>
            <div class="login-menu">
                <ul>
                    <li><a href="/login/">Login</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="login-wrap d-flex align-items-center flex-wrap justify-content-center">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <img src="{% static 'vendors/images/forgot-password.png' %}" alt="">
                </div>
                <div class="col-md-6">
                    <div class="login-box bg-white box-shadow border-radius-10">
                        <div class="login-title">
                            <h2 class="text-center text-primary">Forgot Password</h2>
                        </div>
                        <h6 class="mb-20">Enter your Username to reset your password</h6>
                        <form action="/email-forgotpassword/" method="POST">
                        {% csrf_token %}
                        {% if msg %}

                        <center style ="color: red ;">{{msg}} </center> 

                        {% endif %}
                            <div class="input-group custom">
                                <input type="text" class="form-control form-control-lg" placeholder="UserName" name="username" required>
                                <div class="input-group-append custom">
                                    <span class="input-group-text"><i class="fa fa-envelope-o" aria-hidden="true"></i></span>
                                </div>
                            </div>
                            <div class="row align-items-center">
                                <div class="col-5">
                                    <div class="input-group mb-0">
                                        
											<input class="btn btn-primary btn-lg btn-block" type="submit" value="Submit">
									
                                       <!-- <a class="btn btn-primary btn-lg btn-block" href="index.html">Submit</a> -->
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="font-16 weight-600 text-center" data-color="#707373">OR</div>
                                </div>
                                <div class="col-5">
                                    <div class="input-group mb-0">
                                        <a class="btn btn-outline-primary btn-lg btn-block" href="/login/">Login</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- js -->
    <script src="{% static 'vendors/scripts/core.js' %}"></script>
    <script src="{% static 'vendors/scripts/script.min.js' %}"></script>
    <script src="{% static 'vendors/scripts/process.js' %}"></script>
    <script src="{% static 'vendors/scripts/layout-settings.js' %}"></script>
</body>

</html>

Admin/templates/adminbase.html
<!DOCTYPE html>
<html>
{% load static %}

<head>
    <meta charset="utf-8">
    <title>Employee Management</title>

    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'vendors/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'vendors/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'vendors/images/favicon-16x16.png' %}">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/core.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/icon-font.min.css' %}">
    <link rel="stylesheet" type="text/css"
        href="{% static 'src/plugins/datatables/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css"
        href="{% static 'src/plugins/datatables/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/style.css' %}">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119386393-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-119386393-1');
    </script>
</head>

<body>
    <div class="pre-loader">
        <div class="pre-loader-box">
            <div class="loader-logo"><img src="{% static 'vendors/images/logo-icon.png' %}" alt=""></div>
            <div class='loader-progress' id="progress_div">
                <div class='bar' id='bar1'></div>
            </div>

        </div>
    </div>

    <div class="header">
        <div class="header-left">
            <div class="menu-icon dw dw-menu"></div>
            <div class="search-toggle-icon dw dw-search2" data-toggle="header_search"></div>

        </div>
        <div class="header-right">

            <div class="user-info-dropdown">
                <div class="dropdown">
                    <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                        <span class="user-icon">
                            {% if request.user.userprofile_set.first.profilePicture %}
                            <img style="width:40px; height:40px;border-radius:50%;"
                                src="{{request.user.userprofile_set.first.profilePicture.url}}" alt="">
                            {% else %}
                            <img style="width:40px; height:40px;border-radius:50%;"
                                src="{% static 'vendors/images/photo1.jpg' %}" alt="">
                            {% endif %}

                        </span>
                        <span class="user-name">{{request.user.username}}</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                        <a class="dropdown-item" href="/profile/"><i class="dw dw-user1"></i> Profile</a>
                        <a class="dropdown-item" href="/changepass/"><i class="dw dw-settings2"></i> Change Password</a>
                        <a class="dropdown-item" href="/logout/"><i class="dw dw-logout"></i> Logout</a>
                    </div>
                </div>
            </div>

        </div>
    </div>



    <div class="left-side-bar">
        <div class="brand-logo">
            <a href="/">
                <img src="{% static 'vendors/images/deskapp-logo-white (2).png' %}" alt="" class="dark-logo">
                <img src="{% static 'vendors/images/deskapp-logo-white (2).png' %}" alt="" class="light-logo">
            </a>
            <div class="close-sidebar" data-toggle="left-sidebar-close">
                <i class="ion-close-round"></i>
            </div>
        </div>
        <div class="menu-block customscroll">
            <div class="sidebar-menu">
                <ul id="accordion-menu">
                    {% if request.user.userprofile_set.first.userType == "Admin" %}
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle">
                            <span class="micon dw dw-house-1"></span><span class="mtext">Admin</span>
                        </a>

                        <ul>


                            <li class="dropdown">
                                <a href="javascript:;" class="dropdown-toggle">
                                    <span class="micon dw dw-edit2"></span><span class="mtext">Users</span>
                                </a>
                                <ul class="submenu">
                                    <li><a href="/users/">All Users</a></li>
                                    <li><a href="/managers/">Managers </a></li>
                                    <li><a href="/all-hr/">All HR </a></li>
                                    <li><a href="/employees/">Employees </a></li>
                                </ul>
                            </li>

                    </li>
                    {% endif %}
                    {% if request.user.userprofile_set.first.userType == "HR" %}
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle">
                            <span class="micon dw dw-edit2"></span><span class="mtext">HR</span>
                        </a>
                        <ul class="submenu">

                            <li><a href="/attendance/">Attendance</a></li>
                            <li><a href="/timesheet/">Timesheet</a></li>
                            <li><a href="/leave-application/">Leave Application</a></li>
                            <li><a href="/assign-interview/">Assign Inerview</a></li>
                            <li><a href="/search-candidate/">Search Candidate</a></li>
                            <li><a href="/recruit-notice/">Recruitment Notice</a></li>
                            <li><a href="/result-publish/">Result Publish</a></li>
                            <li><a href="/manage-employee/">Manage Employee</a></li>
                        </ul>
                    </li>
                    {% endif %}
                    {% if request.user.userprofile_set.first.userType == "Employee" %}
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle">
                            <span class="micon dw dw-library"></span><span class="mtext">Employee</span>
                        </a>
                        <ul class="submenu">
                            <li><a href="/attendance/">Attendance</a></li>
                            <li><a href="/timesheet/">Timesheet</a></li>
                            <li><a href="/leave-application/">Leave Application</a></li>
                            <li><a href="/assigned-work/">Assigned Work</a></li>

                        </ul>
                    </li>
                    {% endif %}
                    {% if request.user.userprofile_set.first.userType == "Manager" %}
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle">
                            <span class="micon dw dw-apartment"></span><span class="mtext">Manager</span>
                        </a>
                        <ul class="submenu">
                            <li><a href="/attendance/">Attendance</a></li>
                            <li><a href="/timesheet/">Timesheet</a></li>
                            <li><a href="/interviews/">Interviews</a></li>
                            <li><a href="/assign-work/">Assign Work</a></li>
                            <li><a href="/given-work/">Work Provided</a></li>
                            <li><a href="/attendance-details/">Attendance Details</a></li>
                            <li><a href="/la-details/">LeaveApplicaion Details</a></li>
                        </ul>
                    </li>

                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <div class="mobile-menu-overlay"></div>




    {%block content %} {% endblock %}

    <!-- js -->
    <script src="{% static 'vendors/scripts/core.js' %}"></script>
    <script src="{% static 'vendors/scripts/script.min.js' %}"></script>
    <script src="{% static 'vendors/scripts/process.js' %}"></script>
    <script src="{% static 'vendors/scripts/layout-settings.js' %}"></script>
    <script src="{% static 'src/plugins/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'vendors/scripts/dashboard.js' %}"></script>

</body>

</html>

Admin/templates/assign-interview.html
{% extends 'adminbase.html' %}
{% block content %}
{% load static %}

    <div class="page-wrapper" style="margin-left: 350px;padding-top: 100px;">
        <div class="content">
            <div class="row">
                <div class="col-lg-8">
                    <h1 class="page-title">Assign Interview</h1>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-lg-8 offset-lg-2">
                    <form action="/assign-interview/" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="title">Manager:</label>
                            <select class="form-control" name='manager' required> 
                                {% for u in user %}
                                <option value="{{u.id}}">{{u.user.first_name}} {{u.user.last_name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Candidate Name:</label>
                            <input type="text" name="name" placeholder="Candidate Name.." class="form-control" required />
                        </div>
                        <div class="form-group">
                            <label>Candidate Email:</label>
                            <input type="email" name="email" placeholder="Candidate Email.." class="form-control" required />
                        </div>
                        <div class="form-group">
                            <label>Description:</label>
                            <textarea cols="30" rows="4" placeholder="Candidate Description.." required name="description" class="form-control"></textarea>
                        </div>

                        <div class="m-t-20 text-center">
                            <input type="submit" class="btn btn-primary submit-btn" value="Submit">
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>


{% endblock %}

Admin/templates/attendance.html
{% extends 'adminbase.html' %}
{% block content %}
{% load static %}

    <div class="page-wrapper" style="margin-left: 350px;padding-top: 100px;">
        <div class="content">
            <div class="row">

                <div class="pd-20 col-sm-4 col-3">
                    <h4 class="text-blue h4">Attendance Sheet</h4>
                </div>

            </div>
            <div class="row mt-5">
                <div class="col-lg-8 offset-lg-2">
                    <form action="/attendance/" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if msg %}
                      <center style ="color: red ;">{{msg}} </center> 

                    {% endif %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="name">Employee Name:</label>
                                    <input type="text" value="{{request.user.first_name}} {{request.user.last_name}}" class="form-control" disabled>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="number">Contact No:</label>
                                    <input type="number" class="form-control" id="number" value="{{request.user.userprofile_set.first.contact_No}}" disabled>
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="date">Date:</label>
                                    <input type="date" class="form-control" id="date" name="date" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="date">Status Now:</label>
                                    <Select  class="form-control" name="status" required>
                                    <option>Absent</option>
                                    <option>Present</option>
                                    </select>
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="date">In Time:</label>
                                    <input type="time" class="form-control" id="in_time" name="in_time" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="date">Out Time:</label>
                                    <input type="time" class="form-control" id="out_time" name="out_time" required>
                                </div>
                            </div>
                        </div>

                        <div class="m-t-20 text-center">
                            <input type="submit" class="btn btn-primary submit-btn" value="Submit">
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}